#!/bin/bash
#SBATCH --job-name=ln_0807
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00

python -u ln_qsm_0807.py -b_fmax 0.005 -nr 1000 >data/0807/qsm_0.005.txt 
python -u ln_qsm_0807.py -b_fmax 0.01 -nr 1000 >data/0807/qsm_0.01.txt 
python -u ln_qsm_0807.py -b_fmax 0.03 -nr 1000 >data/0807/qsm_0.03.txt
python -u ln_qsm_0807.py -b_fmax 0.1 -nr 1000 >data/0807/qsm_0.1.txt  
python -u ln_qsm_0807.py -b_fmax 0.2 -nr 1000 >data/0807/qsm_0.2.txt 
python -u ln_qsm_0807.py -b_fmax 0.3 -nr 1000 >data/0807/qsm_0.3.txt 
python -u ln_qsm_0807.py -b_fmax 0.4 -nr 1000 >data/0807/qsm_0.4.txt 
python -u ln_qsm_0807.py -b_fmax 0.5 -nr 1000 >data/0807/qsm_0.5.txt 
python -u ln_qsm_0807.py -b_fmax 0.6 -nr 1000 >data/0807/qsm_0.6.txt 
python -u ln_qsm_0807.py -b_fmax 0.7 -nr 1000 >data/0807/qsm_0.7.txt 
python -u ln_qsm_0807.py -b_fmax 0.8 -nr 1000 >data/0807/qsm_0.8.txt 
python -u ln_qsm_0807.py -b_fmax 0.9 -nr 1000 >data/0807/qsm_0.9.txt
python -u ln_qsm_0807.py -b_fmax 1.0 -nr 1000 >data/0807/qsm_1.0.txt 
python -u ln_qsm_0807.py -b_fmax 1.1 -nr 1000 >data/0807/qsm_1.1.txt
python -u ln_qsm_0807.py -b_fmax 1.2 -nr 1000 >data/0807/qsm_1.2.txt
python -u ln_qsm_0807.py -b_fmax 1.4 -nr 1000 >data/0807/qsm_1.4.txt
python -u ln_qsm_0807.py -b_fmax 1.6 -nr 1000 >data/0807/qsm_1.6.txt
python -u ln_qsm_0807.py -b_fmax 1.8 -nr 1000 >data/0807/qsm_1.8.txt
python -u ln_qsm_0807.py -b_fmax 2.0 -nr 1000 >data/0807/qsm_2.0.txt
python -u ln_qsm_0807.py -b_fmax 2.5 -nr 1000 >data/0807/qsm_2.5.txt
python -u ln_qsm_0807.py -b_fmax 3.0 -nr 1000 >data/0807/qsm_3.0.txt
python -u ln_qsm_0807.py -b_fmax 3.5 -nr 1000 >data/0807/qsm_3.5.txt
python -u ln_qsm_0807.py -b_fmax 4.0 -nr 1000 >data/0807/qsm_4.0.txt
python -u ln_qsm_0807.py -b_fmax 4.5 -nr 1000 >data/0807/qsm_4.5.txt
python -u ln_qsm_0807.py -b_fmax 5.0 -nr 1000 >data/0807/qsm_5.0.txt
