#!/bin/bash
#SBATCH --job-name=sc_0626_4
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00



python -u na_3_ave_czk_0608.py -pt 1 -b 10 >data/0626/arp_3_czk_b10.txt
python -u na_3_ave_czk_0608.py -pt 1 -b 30 >data/0626/arp_3_czk_b30.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 50 >data/0626/arp_3_czk_b50.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 70 >data/0626/arp_3_czk_b70.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 90 >data/0626/arp_3_czk_b90.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 110 >data/0626/arp_3_czk_b110.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 130 >data/0626/arp_3_czk_b130.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 150 >data/0626/arp_3_czk_b150.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 170 >data/0626/arp_3_czk_b170.txt 
python -u na_3_ave_czk_0608.py -pt 1 -b 200 >data/0626/arp_3_czk_b200.txt 
