#!/bin/bash
#SBATCH --job-name=sc_0424_1
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00


python -u na_5_ave_czk.py -pt 2 -b 30 >data/0403/sp_5_czk_b30.txt
python -u na_5_ave_czk.py -pt 2 -b 50 >data/0403/sp_5_czk_b50.txt 
python -u na_5_ave_czk.py -pt 2 -b 70 >data/0403/sp_5_czk_b70.txt 
