#!/bin/bash
#SBATCH --job-name=sc_0614_3
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00



python -u na_5_ave_czk_0608.py -pt 1 -b 130 >data/0613/arp_5_czk_b130.txt
python -u na_5_ave_czk_0608.py -pt 1 -b 150 >data/0613/arp_5_czk_b150.txt
python -u na_5_ave_czk_0608.py -pt 1 -b 170 >data/0613/arp_5_czk_b170.txt  
