#!/bin/bash
#SBATCH --job-name=sc_0424_2
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00


python -u na_5_ave_czk.py -pt 2 -b 90 >data/0403/sp_5_czk_b90.txt
python -u na_5_ave_czk.py -pt 2 -b 110 >data/0403/sp_5_czk_b110.txt 
python -u na_5_ave_czk.py -pt 2 -b 130 >data/0403/sp_5_czk_b130.txt 
