#!/bin/bash
#SBATCH --job-name=sc_0613_2
#SBATCH -N 1
#SBATCH -p bdwall
#SBATCH --ntasks-per-node=36
#SBATCH -t 80:00:00


python -u na_5_ave_czk_0608.py -pt 2 -b 70 >data/0613/sp_5_czk_b70.txt
python -u na_5_ave_czk_0608.py -pt 2 -b 90 >data/0613/sp_5_czk_b90.txt
python -u na_5_ave_czk_0608.py -pt 2 -b 110 >data/0613/sp_5_czk_b110.txt  
